// AUTO-GENERATED by scripts/build-image-map.js — real product photos from web image search.
// Do not edit by hand. Re-run the script after refreshing image searches.

export const categoryImages: Record<string, string> = {
  "fruits": "https://sfile.chatglm.cn/images-ppt/00ca13263086.jpg",
  "vegetables": "https://sfile.chatglm.cn/images-ppt/46d9f8df910f.jpg",
  "dairy": "https://sfile.chatglm.cn/images-ppt/4dd7a7ea0506.jpg",
  "snacks": "https://sfile.chatglm.cn/images-ppt/c9d3ac9d5cfb.jpg",
  "beverages": "https://sfile.chatglm.cn/images-ppt/f5a3dbd8eadc.jpg",
  "bakery": "https://sfile.chatglm.cn/images-ppt/0bfaf19df643.jpg",
  "personal-care": "https://sfile.chatglm.cn/images-ppt/100bbdf9aedf.jpg",
  "baby-care": "https://sfile.chatglm.cn/images-ppt/7d6a86695650.jpg",
  "cleaning": "https://sfile.chatglm.cn/images-ppt/e62125633201.jpg",
  "frozen": "https://sfile.chatglm.cn/images-ppt/eb162e683866.jpg",
  "instant": "https://sfile.chatglm.cn/images-ppt/ad87568cf8d6.webp",
  "medicines": "https://sfile.chatglm.cn/images-ppt/da343c608270.jpg",
  "pet-care": "https://sfile.chatglm.cn/images-ppt/2b0d52301287.png",
  "electronics": "https://sfile.chatglm.cn/images-ppt/c89918314d4a.jpg",
  "home": "https://sfile.chatglm.cn/images-ppt/d952fcf272a1.jpg"
};

export const productImagesByCategory: Record<string, string[]> = {
  "fruits": [
    "https://sfile.chatglm.cn/images-ppt/00ca13263086.jpg",
    "https://sfile.chatglm.cn/images-ppt/e7490fd80ea8.jpg",
    "https://sfile.chatglm.cn/images-ppt/e7cc3ad71d1b.jpg",
    "https://sfile.chatglm.cn/images-ppt/144dfc9f5fa4.jpg",
    "https://sfile.chatglm.cn/images-ppt/3b496810f9cc.jpg",
    "https://sfile.chatglm.cn/images-ppt/635c26f6350e.jpg",
    "https://sfile.chatglm.cn/images-ppt/5d492d7d1a53.jpg",
    "https://sfile.chatglm.cn/images-ppt/7b93cef80d90.jpg"
  ],
  "vegetables": [
    "https://sfile.chatglm.cn/images-ppt/46d9f8df910f.jpg",
    "https://sfile.chatglm.cn/images-ppt/3329c8333b1c.jpg",
    "https://sfile.chatglm.cn/images-ppt/f639055e77ad.jpg",
    "https://sfile.chatglm.cn/images-ppt/16300ce1bdf6.jpg",
    "https://sfile.chatglm.cn/images-ppt/42716d08f1a8.jpg",
    "https://sfile.chatglm.cn/images-ppt/6205ec520abf.jpg",
    "https://sfile.chatglm.cn/images-ppt/314fdf90bfcd.jpg",
    "https://sfile.chatglm.cn/images-ppt/4cb0a6a3880c.jpg"
  ],
  "dairy": [
    "https://sfile.chatglm.cn/images-ppt/4dd7a7ea0506.jpg",
    "https://sfile.chatglm.cn/images-ppt/30de6fe706a9.png",
    "https://sfile.chatglm.cn/images-ppt/c4f0a5c18488.jpg",
    "https://sfile.chatglm.cn/images-ppt/add5082cee4e.jpg",
    "https://sfile.chatglm.cn/images-ppt/41f03e7ca494.jpg",
    "https://sfile.chatglm.cn/images-ppt/0fb9743ea51f.jpg",
    "https://sfile.chatglm.cn/images-ppt/8f9b2f52eef0.jpeg",
    "https://sfile.chatglm.cn/images-ppt/437a3fe65c7b.png"
  ],
  "snacks": [
    "https://sfile.chatglm.cn/images-ppt/c9d3ac9d5cfb.jpg",
    "https://sfile.chatglm.cn/images-ppt/e44d1cd103e6.jpg",
    "https://sfile.chatglm.cn/images-ppt/f9096a555c22.jpg",
    "https://sfile.chatglm.cn/images-ppt/64ef183f3dc3.jpg",
    "https://sfile.chatglm.cn/images-ppt/ea6e39a0be20.jpg",
    "https://sfile.chatglm.cn/images-ppt/13f6341d0bf2.jpg",
    "https://sfile.chatglm.cn/images-ppt/817a1bdb2f48.jpg",
    "https://sfile.chatglm.cn/images-ppt/986bb53ec4da.jpg"
  ],
  "beverages": [
    "https://sfile.chatglm.cn/images-ppt/f5a3dbd8eadc.jpg",
    "https://sfile.chatglm.cn/images-ppt/3401a9ed3aa5.jpeg",
    "https://sfile.chatglm.cn/images-ppt/15c195a3b91a.jpeg",
    "https://sfile.chatglm.cn/images-ppt/ddb05723c4d1.jpg",
    "https://sfile.chatglm.cn/images-ppt/bc0dccd9a96e.jpg",
    "https://sfile.chatglm.cn/images-ppt/82f2594f983d.jpg",
    "https://sfile.chatglm.cn/images-ppt/13c272006e1b.jpg",
    "https://sfile.chatglm.cn/images-ppt/c415bb10e990.png"
  ],
  "bakery": [
    "https://sfile.chatglm.cn/images-ppt/0bfaf19df643.jpg",
    "https://sfile.chatglm.cn/images-ppt/2a8bfa1d3871.jpg",
    "https://sfile.chatglm.cn/images-ppt/2b77633bee25.jpg",
    "https://sfile.chatglm.cn/images-ppt/07145bcdd3b8.jpeg",
    "https://sfile.chatglm.cn/images-ppt/55f07816f540.jpg",
    "https://sfile.chatglm.cn/images-ppt/204969e9b147.jpg",
    "https://sfile.chatglm.cn/images-ppt/b866e2d6576c.jpg",
    "https://sfile.chatglm.cn/images-ppt/a18fe52d8a4c.jpg"
  ],
  "personal-care": [
    "https://sfile.chatglm.cn/images-ppt/100bbdf9aedf.jpg",
    "https://sfile.chatglm.cn/images-ppt/f32b9e744035.jpeg",
    "https://sfile.chatglm.cn/images-ppt/30b975d1019f.jpg",
    "https://sfile.chatglm.cn/images-ppt/2e7f94f3555a.jpg",
    "https://sfile.chatglm.cn/images-ppt/4d884342f10a.jpg",
    "https://sfile.chatglm.cn/images-ppt/e05fdf306a81.jpg",
    "https://sfile.chatglm.cn/images-ppt/04ccaa383b5c.png",
    "https://sfile.chatglm.cn/images-ppt/ac6045a42bac.jpg"
  ],
  "baby-care": [
    "https://sfile.chatglm.cn/images-ppt/7d6a86695650.jpg",
    "https://sfile.chatglm.cn/images-ppt/648e1e455a4d.jpg",
    "https://sfile.chatglm.cn/images-ppt/b96c9f0f3117.jpeg",
    "https://sfile.chatglm.cn/images-ppt/0bd92fc37d9d.jpg",
    "https://sfile.chatglm.cn/images-ppt/52e6fa363ec9.jpg",
    "https://sfile.chatglm.cn/images-ppt/f31e3919a561.jpg",
    "https://sfile.chatglm.cn/images-ppt/1c0ee08906bd.jpg",
    "https://sfile.chatglm.cn/images-ppt/8dc3aafd67f5.jpg"
  ],
  "cleaning": [
    "https://sfile.chatglm.cn/images-ppt/e62125633201.jpg",
    "https://sfile.chatglm.cn/images-ppt/9605eb200359.jpg",
    "https://sfile.chatglm.cn/images-ppt/c3c3cb2cb333.jpg",
    "https://sfile.chatglm.cn/images-ppt/2862cb7c895b.jpg",
    "https://sfile.chatglm.cn/images-ppt/d8b62c4d7d73.jpg",
    "https://sfile.chatglm.cn/images-ppt/5ab16e8b4717.jpg",
    "https://sfile.chatglm.cn/images-ppt/f00e597b3a3d.jpg",
    "https://sfile.chatglm.cn/images-ppt/82240923507d.jpeg"
  ],
  "frozen": [
    "https://sfile.chatglm.cn/images-ppt/eb162e683866.jpg",
    "https://sfile.chatglm.cn/images-ppt/a6a522adba1d.png",
    "https://sfile.chatglm.cn/images-ppt/b481cbad3e50.png",
    "https://sfile.chatglm.cn/images-ppt/6e8f27d85cfe.jpg",
    "https://sfile.chatglm.cn/images-ppt/5ca684394e53.jpg",
    "https://sfile.chatglm.cn/images-ppt/22538a6a1edc.jpg",
    "https://sfile.chatglm.cn/images-ppt/3ff6d16ebb76.jpg",
    "https://sfile.chatglm.cn/images-ppt/7012f363e49e.jpg"
  ],
  "instant": [
    "https://sfile.chatglm.cn/images-ppt/ad87568cf8d6.webp",
    "https://sfile.chatglm.cn/images-ppt/54c4834aa58d.png",
    "https://sfile.chatglm.cn/images-ppt/15303fe3a386.jpg",
    "https://sfile.chatglm.cn/images-ppt/534c1641c655.jpg",
    "https://sfile.chatglm.cn/images-ppt/22c9243f7b1a.jpeg",
    "https://sfile.chatglm.cn/images-ppt/396009fd8540.jpg",
    "https://sfile.chatglm.cn/images-ppt/09339b2b5e61.png",
    "https://sfile.chatglm.cn/images-ppt/67c0cfe528dd.jpg"
  ],
  "medicines": [
    "https://sfile.chatglm.cn/images-ppt/da343c608270.jpg",
    "https://sfile.chatglm.cn/images-ppt/21124cbc7adb.jpg",
    "https://sfile.chatglm.cn/images-ppt/7dffbc3911f7.jpeg",
    "https://sfile.chatglm.cn/images-ppt/c0f3aade2c69.jpg",
    "https://sfile.chatglm.cn/images-ppt/9d417c51d29c.jpg",
    "https://sfile.chatglm.cn/images-ppt/1ee711e75edc.jpg",
    "https://sfile.chatglm.cn/images-ppt/eeb5726fc63c.jpg",
    "https://sfile.chatglm.cn/images-ppt/be477e2cbd7a.jpg"
  ],
  "pet-care": [
    "https://sfile.chatglm.cn/images-ppt/2b0d52301287.png",
    "https://sfile.chatglm.cn/images-ppt/cf5ba41363b0.jpg",
    "https://sfile.chatglm.cn/images-ppt/e2a1e6dcac9b.jpg",
    "https://sfile.chatglm.cn/images-ppt/3e78af522827.jpg",
    "https://sfile.chatglm.cn/images-ppt/77d66fd03061.jpg",
    "https://sfile.chatglm.cn/images-ppt/7c2e23a2bf29.png",
    "https://sfile.chatglm.cn/images-ppt/8a72c63cc4c8.jpg",
    "https://sfile.chatglm.cn/images-ppt/501bf3723a60.jpg"
  ],
  "electronics": [
    "https://sfile.chatglm.cn/images-ppt/c89918314d4a.jpg",
    "https://sfile.chatglm.cn/images-ppt/7d8f60f4fa2f.jpg",
    "https://sfile.chatglm.cn/images-ppt/6bc5cabfd489.jpg",
    "https://sfile.chatglm.cn/images-ppt/ebd780576770.jpg",
    "https://sfile.chatglm.cn/images-ppt/b4066378edd8.png",
    "https://sfile.chatglm.cn/images-ppt/a583794c955a.jpg",
    "https://sfile.chatglm.cn/images-ppt/79564e2ed1f3.jpg",
    "https://sfile.chatglm.cn/images-ppt/aaa11c6f5584.jpg"
  ],
  "home": [
    "https://sfile.chatglm.cn/images-ppt/d952fcf272a1.jpg",
    "https://sfile.chatglm.cn/images-ppt/6764e7cbc9c1.jpg",
    "https://sfile.chatglm.cn/images-ppt/8f1bc19a1313.jpg",
    "https://sfile.chatglm.cn/images-ppt/5ad8f029ef65.jpeg",
    "https://sfile.chatglm.cn/images-ppt/2eba18619dfe.jpg",
    "https://sfile.chatglm.cn/images-ppt/851ac2e2ca86.jpg",
    "https://sfile.chatglm.cn/images-ppt/6e7dba6a6a38.jpg",
    "https://sfile.chatglm.cn/images-ppt/bfda48b6fa0a.png"
  ]
};
